name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install All Dependencies
        run: |
          pip install dvc dvc-s3 xgboost pandas scikit-learn matplotlib plotly pyyaml kaggle mlflow dagshub

      - name: Execute Pipeline (dvc repro)
        env:
          # This connects your CI/CD to MLflow on DagsHub
          MLFLOW_TRACKING_URI: https://dagshub.com/SAIF-BT/Predictive_maintenance.mlflow
          MLFLOW_TRACKING_USERNAME: SAIF-BT
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Configure DVC Remote
          dvc remote add origin https://dagshub.com/SAIF-BT/Predictive_maintenance.dvc --force
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user SAIF-BT
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
          
          # Pull existing data to avoid running Kaggle Ingestion
          dvc pull -r origin
          
          # Reproduce the pipeline starting FROM the training stage
          dvc repro train