name: Full-MLOps-Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'src/**'
      - 'params.yaml'
      - '.github/workflows/mlops.yaml'

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Speeds up future runs

      - name: Install All Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc dvc-s3 xgboost pandas scikit-learn matplotlib plotly pyyaml kaggle

      - name: Configure DVC Remote
        env:
          dvc_token: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote add origin https://dagshub.com/SAIF-BT/Predictive_maintenance.dvc || true
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user SAIF-BT
          dvc remote modify origin --local password $dvc_token

      - name: Pull Data from DagsHub
        run: |
          # This brings in the data you already uploaded, 
          # so 'dvc repro' won't feel the need to run 'ingest' (Kaggle)
          dvc pull -r origin

      - name: Execute Pipeline (dvc repro)
        run: |
          # DVC is smart: if it sees the data from 'dvc pull', 
          # it will skip 'ingest' and move to 'preprocess'
          dvc repro

      - name: Push Updated Model & Metrics
        env:
          dvc_token: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Push any newly trained model to DagsHub
          dvc push -r origin
          
          # Push the updated dvc.lock back to GitHub
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dvc.lock models/metrics.json || echo "No changes to commit"
          
          # [skip ci] is mandatory to avoid infinite loops!
          git commit -m "🚀 Automated Model Update [skip ci]" || echo "No changes to commit"
          git push origin main